language: python
python:
  - "2.6"
  - "2.7"
install: 
  - pip install -e .
  - pip install twisted
  - pip install coveralls
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
script: 
  - py.test -x -v --log=debug --cov pynetworking --cov-config .coveragerc tests/
after_success:
  - coveralls -v

