language: python
python:
  - "2.7"
install: 
  - pip install -e . --use-mirrors
  - pip install twisted
  - pip install coveralls
  - pip install coverage
  - pip install pytest
script: 
  - coverage run --source pynetworking setup.py tests
after_success:
  - coveralls

