language: python
python:
  - "2.7"
install: 
  - pip install .
  - pip install twisted
  - pip install coveralls
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
script: 
  - py.test --cov pynetworking tests/
after_success:
  - coveralls

