# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "master-centos" do |cfg|
    config.vm.box = "chef/centos-6.5"
    cfg.vm.network :private_network, ip:"192.168.221.254"
    cfg.vm.hostname = "centos.local"
    cfg.vm.network "forwarded_port", guest: 8080, host: 8081
    cfg.vm.provision "shell", inline: "su"
    cfg.vm.provision "shell", inline: "yum install python-devel -y"
    cfg.vm.provision "shell", inline: "yum install gcc -y"
    cfg.vm.provision "shell", inline: "yum install gcc-c++ -y"
    cfg.vm.provision "shell", inline: "wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate"
    cfg.vm.provision "shell", inline: "python get-pip.py"
    cfg.vm.provision "shell", inline: "pip install py-networking"
    cfg.vm.provision "shell", inline: "exit"
    cfg.vm.provider :virtualbox do |v, override|
      v.gui = true
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--nic2", "intnet"]
      v.customize ["modifyvm", :id, "--nictype2", "Am79C970A"]
    end
  end
  config.vm.define "master-debian" do |cfg|
    config.vm.box = "puphpet/debian75-x64"
    cfg.vm.network :private_network, ip:"192.168.221.254"
    cfg.vm.hostname = "debian.local"
    cfg.vm.network "forwarded_port", guest: 8080, host: 8081
    cfg.vm.provision "shell", inline: "su"
    cfg.vm.provision "shell", inline: "apt-get update"
    cfg.vm.provision "shell", inline: "apt-get install python-pip -y"
    cfg.vm.provision "shell", inline: "apt-get install python-dev -y"
    cfg.vm.provision "shell", inline: "pip install markupsafe"
    cfg.vm.provision "shell", inline: "pip install py-networking"
    cfg.vm.provision "shell", inline: "exit"
    cfg.vm.provider :virtualbox do |v, override|
      v.gui = true
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--nic2", "intnet"]
      v.customize ["modifyvm", :id, "--nictype2", "Am79C970A"]
    end
  end
  config.vm.define "master-fedora" do |cfg|
    config.vm.box = "chef/fedora-20"
    cfg.vm.network :private_network, ip:"192.168.221.254"
    cfg.vm.hostname = "fedora.local"
    cfg.vm.network "forwarded_port", guest: 8080, host: 8081
    cfg.vm.provision "shell", inline: "su"
    cfg.vm.provision "shell", inline: "yum install python-devel -y"
    cfg.vm.provision "shell", inline: "yum install gcc -y"
    cfg.vm.provision "shell", inline: "yum install gcc-c++ -y"
    cfg.vm.provision "shell", inline: "wget https://bootstrap.pypa.io/get-pip.py"
    cfg.vm.provision "shell", inline: "python get-pip.py"
    cfg.vm.provision "shell", inline: "pip install py-networking"
    cfg.vm.provision "shell", inline: "exit"
    cfg.vm.provider :virtualbox do |v, override|
      v.gui = true
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--nic2", "intnet"]
      v.customize ["modifyvm", :id, "--nictype2", "Am79C970A"]
    end
  end
  config.vm.define "master-ubuntu" do |cfg|
    config.vm.box = "puphpet/ubuntu1404-x64"
    cfg.vm.network :private_network, ip:"192.168.221.254"
    cfg.vm.hostname = "ubuntu.local"
    cfg.vm.network "forwarded_port", guest: 8080, host: 8081
    cfg.vm.provision "shell", inline: "su"
    cfg.vm.provision "shell", inline: "apt-get update"
    cfg.vm.provision "shell", inline: "apt-get install python-pip -y"
    cfg.vm.provision "shell", inline: "apt-get install python-dev -y"
    cfg.vm.provision "shell", inline: "pip install py-networking"
    cfg.vm.provision "shell", inline: "exit"
    cfg.vm.provider :virtualbox do |v, override|
      v.gui = true
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--nic2", "intnet"]
      v.customize ["modifyvm", :id, "--nictype2", "Am79C970A"]
    end
  end
end

